services:
  redis:
    image: "valkey/valkey:alpine"
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 1s
      timeout: 10s
      retries: 5
    ports:
      - "6379:6379"
    # Do not persist data across container restarts for local development
    command: valkey-server --save "" --appendonly no
  db:
    image: "postgres:17"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_MULTIPLE_DATABASES: "myapp,postgres:pgtest,pgtest"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 10s
      retries: 5
    volumes:
      - ./apps/platform/scripts/create-multiple-databases.sh:/docker-entrypoint-initdb.d/create-multiple-databases.sh
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
