name: CI

on:
  push:
    branches: [main]

jobs:
  placeholder_job:
    name: Placeholder job
    runs-on: ubuntu-latest    
    steps:
      - name: Placeholder step
        run: echo "This is just a placeholder to satisfy nx sharedGlobals"